baseURL = 'https://bluez.org/'
languageCode = 'en-us'
title = 'BlueZ - Official Linux Bluetooth Protocol Stack'

[params]
  description = 'BlueZ is the official Linux Bluetooth protocol stack. Part of the mainline kernel, it supports Classic Bluetooth and Low Energy with D-Bus and socket APIs.'
  copyrightYearStart = 2000

[pagination]
  pagerSize = 12

[taxonomies]

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
